language: ruby
script:
  - bundle exec rake spec
  - gem build recurly.gemspec
cache: bundler
sudo: false
before_install:
  - yes | gem update --system
  - gem update bundler
rvm:
  - jruby-9.1
  - jruby-9000
  - 1.9.3-p551
  - 2.0.0-p648
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - 2.7
env:
  - XML=rexml
  - XML=nokogiri
matrix:
  allow_failures:
    - rvm: 2.7
    - rvm: 1.9.3-p551
    - rvm: 2.0.0-p648
    - rvm: 2.1
    - rvm: 2.2
    - rvm: 2.3
    - rvm: jruby-9.1.9.0
    - rvm: jruby-9.1
    - rvm: jruby-9000
